// <auto-generated />
// Built from: hl7.fhir.r4.core version: 4.0.1

using Fhir.R4.Models;

namespace Fhir.R4.ValueSets
{
  /// <summary>
  /// Example codes indicating the outcome of a care plan activity. Note that these are in no way complete and might not even be appropriate for some uses.
  /// </summary>
  public static class CarePlanActivityOutcomeCodes
  {
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DeficientKnowledgeDiagnosticTest = new Coding
    {
      Code = "129862009",
      Display = "Deficient knowledge: diagnostic test",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DeficientKnowledgeOfDietaryRegimen = new Coding
    {
      Code = "129863004",
      Display = "Deficient knowledge of dietary regimen",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DeficientKnowledgeDiseaseProcess = new Coding
    {
      Code = "129864005",
      Display = "Deficient knowledge: disease process",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DeficientKnowledgeOfFluidVolumeManagement = new Coding
    {
      Code = "129865006",
      Display = "Deficient knowledge of fluid volume management",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DeficientKnowledgeMedicationRegimen = new Coding
    {
      Code = "129866007",
      Display = "Deficient knowledge: medication regimen",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DeficientKnowledgeOfSafetyPrecautions = new Coding
    {
      Code = "129867003",
      Display = "Deficient knowledge of safety precautions",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DeficientKnowledgeTherapeuticRegimen = new Coding
    {
      Code = "129868008",
      Display = "Deficient knowledge: therapeutic regimen",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PatientMisunderstoodTreatmentInstructions = new Coding
    {
      Code = "182891003",
      Display = "Patient misunderstood treatment instructions",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DemonstratesKnowledgeOfExpectedResponsesToOperativeProcedure = new Coding
    {
      Code = "397588000",
      Display = "Demonstrates knowledge of expected responses to operative procedure",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DemonstratesKnowledgeOfNutritionalRequirementsRelatedToOperativeProcedure = new Coding
    {
      Code = "397598006",
      Display = "Demonstrates knowledge of nutritional requirements related to operative procedure",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DemonstratesKnowledgeOfWoundHealingProcess = new Coding
    {
      Code = "397675006",
      Display = "Demonstrates knowledge of wound healing process",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DemonstratesKnowledgeOfMedicationManagement = new Coding
    {
      Code = "397699006",
      Display = "Demonstrates knowledge of medication management",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DemonstratesKnowledgeOfPainManagement = new Coding
    {
      Code = "397724004",
      Display = "Demonstrates knowledge of pain management",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PatientDoesNotUnderstandWhyTakingAllMedication = new Coding
    {
      Code = "408364003",
      Display = "Patient does not understand why taking all medication",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DeficientKnowledgeOfFamilyPlanningMethods = new Coding
    {
      Code = "423875000",
      Display = "Deficient knowledge of family planning methods",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DeficientKnowledgeOfPreconceptionHealthPractices = new Coding
    {
      Code = "424537004",
      Display = "Deficient knowledge of preconception health practices",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DeficientKnowledge = new Coding
    {
      Code = "54777007",
      Display = "Deficient knowledge",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DeficientKnowledgeOfBreastFeeding = new Coding
    {
      Code = "704375003",
      Display = "Deficient knowledge of breast feeding",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DeficientKnowledgeOfPeritonealDialysis = new Coding
    {
      Code = "704377006",
      Display = "Deficient knowledge of peritoneal dialysis",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DeficientKnowledgeOfSexualBehavior = new Coding
    {
      Code = "704379009",
      Display = "Deficient knowledge of sexual behavior",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DeficientKnowledgeOfOralHygiene = new Coding
    {
      Code = "704381006",
      Display = "Deficient knowledge of oral hygiene",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DeficientKnowledgeOfChildDevelopment = new Coding
    {
      Code = "704383009",
      Display = "Deficient knowledge of child development",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DeficientKnowledgeOfCommunityServices = new Coding
    {
      Code = "704400005",
      Display = "Deficient knowledge of community services",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DeficientKnowledgeOfPhysicalTherapy = new Coding
    {
      Code = "704402002",
      Display = "Deficient knowledge of physical therapy",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DeficientKnowledgeOfFallPrevention = new Coding
    {
      Code = "704403007",
      Display = "Deficient knowledge of fall prevention",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DeficientKnowledgeOfPainManagement = new Coding
    {
      Code = "704404001",
      Display = "Deficient knowledge of pain management",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DeficientKnowledgeOfSymptom = new Coding
    {
      Code = "704406004",
      Display = "Deficient knowledge of symptom",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DeficientKnowledgeOfExercise = new Coding
    {
      Code = "704446005",
      Display = "Deficient knowledge of exercise",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DeficientKnowledgeOfTraditionalTherapy = new Coding
    {
      Code = "704491001",
      Display = "Deficient knowledge of traditional therapy",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DeficientKnowledgeOfBehaviorChangeProcess = new Coding
    {
      Code = "704680001",
      Display = "Deficient knowledge of behavior change process",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DeficientKnowledgeOfPatientControlledAnalgesia = new Coding
    {
      Code = "705086000",
      Display = "Deficient knowledge of patient controlled analgesia",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DeficientKnowledgeOfMedication = new Coding
    {
      Code = "706869001",
      Display = "Deficient knowledge of medication",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DemonstratesKnowledgeOfWhoToContactInMedicalEmergency = new Coding
    {
      Code = "708571001",
      Display = "Demonstrates knowledge of who to contact in medical emergency",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DeficientKnowledgeOfTravelHealth = new Coding
    {
      Code = "713398008",
      Display = "Deficient knowledge of travel health",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DeficientKnowledgeOfParenting = new Coding
    {
      Code = "713447003",
      Display = "Deficient knowledge of parenting",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DeficientKnowledgeOfInfantFeeding = new Coding
    {
      Code = "713448008",
      Display = "Deficient knowledge of infant feeding",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DeficientKnowledgeOfInfantCare = new Coding
    {
      Code = "713449000",
      Display = "Deficient knowledge of infant care",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DeficientKnowledgeOfChildbirth = new Coding
    {
      Code = "713451001",
      Display = "Deficient knowledge of childbirth",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DeficientKnowledgeOfFoetalDevelopment = new Coding
    {
      Code = "713452008",
      Display = "Deficient knowledge of foetal development",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DeficientKnowledgeOfPregnancy = new Coding
    {
      Code = "714670007",
      Display = "Deficient knowledge of pregnancy",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding AbleToAdaptToSensoryChangesInBodyPart = new Coding
    {
      Code = "716391009",
      Display = "Able to adapt to sensory changes in body part",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding AbleToRecognizeNeedForPressureAreaCare = new Coding
    {
      Code = "716438000",
      Display = "Able to recognize need for pressure area care",
      System = "http://snomed.info/sct"
    };
  };
}
