// <auto-generated />
// Built from: hl7.fhir.r4.core version: 4.0.1
  // Option: "NAMESPACE" = "fhirCsR4"

using fhirCsR4.Models;

namespace fhirCsR4.ValueSets
{
  /// <summary>
  /// This value set defines the set of codes that can be used to indicate the marital status of a person.
  /// </summary>
  public static class MaritalStatusCodes
  {
    /// <summary>
    /// Marriage contract has been declared null and to not have existed
    /// </summary>
    public static readonly Coding Annulled_v3_MaritalStatus = new Coding
    {
      Code = "A",
      Display = "Annulled",
      System = "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus"
    };
    /// <summary>
    /// Marriage contract has been declared dissolved and inactive
    /// </summary>
    public static readonly Coding Divorced_v3_MaritalStatus = new Coding
    {
      Code = "D",
      Display = "Divorced",
      System = "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus"
    };
    /// <summary>
    /// Subject to an Interlocutory Decree.
    /// </summary>
    public static readonly Coding Interlocutory_v3_MaritalStatus = new Coding
    {
      Code = "I",
      Display = "Interlocutory",
      System = "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus"
    };
    /// <summary>
    /// Legally Separated
    /// </summary>
    public static readonly Coding LegallySeparated_v3_MaritalStatus = new Coding
    {
      Code = "L",
      Display = "Legally Separated",
      System = "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus"
    };
    /// <summary>
    /// A current marriage contract is active
    /// </summary>
    public static readonly Coding Married_v3_MaritalStatus = new Coding
    {
      Code = "M",
      Display = "Married",
      System = "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus"
    };
    /// <summary>
    /// More than 1 current spouse
    /// </summary>
    public static readonly Coding Polygamous_v3_MaritalStatus = new Coding
    {
      Code = "P",
      Display = "Polygamous",
      System = "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus"
    };
    /// <summary>
    /// No marriage contract has ever been entered
    /// </summary>
    public static readonly Coding NeverMarried_v3_MaritalStatus = new Coding
    {
      Code = "S",
      Display = "Never Married",
      System = "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus"
    };
    /// <summary>
    /// Person declares that a domestic partner relationship exists.
    /// </summary>
    public static readonly Coding DomesticPartner_v3_MaritalStatus = new Coding
    {
      Code = "T",
      Display = "Domestic partner",
      System = "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus"
    };
    /// <summary>
    /// Currently not in a marriage contract.
    /// </summary>
    public static readonly Coding Unmarried_v3_MaritalStatus = new Coding
    {
      Code = "U",
      Display = "unmarried",
      System = "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus"
    };
    /// <summary>
    /// Description:A proper value is applicable, but not known.
    /// 
    ///                         
    ///                            Usage Notes: This means the actual value is not known.  If the only thing that is unknown is how to properly express the value in the necessary constraints (value set, datatype, etc.), then the OTH or UNC flavor should be used.  No properties should be included for a datatype with this property unless:
    /// 
    ///                         
    ///                            Those properties themselves directly translate to a semantic of "unknown".  (E.g. a local code sent as a translation that conveys 'unknown')
    ///                            Those properties further qualify the nature of what is unknown.  (E.g. specifying a use code of "H" and a URL prefix of "tel:" to convey that it is the home phone number that is unknown.)
    /// </summary>
    public static readonly Coding Unknown_v3_NullFlavor = new Coding
    {
      Code = "UNK",
      Display = "unknown",
      System = "http://terminology.hl7.org/CodeSystem/v3-NullFlavor"
    };
    /// <summary>
    /// The spouse has died
    /// </summary>
    public static readonly Coding Widowed_v3_MaritalStatus = new Coding
    {
      Code = "W",
      Display = "Widowed",
      System = "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus"
    };
  };
}
