// <auto-generated />
// Built from: hl7.fhir.r5.core version: 5.0.0-snapshot1
  // Option: "NAMESPACE" = "fhirCsR5"

using fhirCsR5.Models;

namespace fhirCsR5.ValueSets
{
  /// <summary>
  /// Possible values for the workflow status of the comment or assessment, typically used to coordinate workflow around the process of accepting and rejecting changes and comments on the artifact.
  /// </summary>
  public static class ArtifactassessmentWorkflowStatusCodes
  {
    /// <summary>
    /// The comment is resolved and any necessary changes have been applied
    /// </summary>
    public static readonly Coding Applied = new Coding
    {
      Code = "applied",
      Display = "Applied",
      System = "http://hl7.org/fhir/artifactassessment-workflow-status"
    };
    /// <summary>
    /// The comment is acceptable, but resolution of the comment and application of any associated changes have been deferred
    /// </summary>
    public static readonly Coding Deferred = new Coding
    {
      Code = "deferred",
      Display = "Deferred",
      System = "http://hl7.org/fhir/artifactassessment-workflow-status"
    };
    /// <summary>
    /// The comment is a duplicate of another comment already received
    /// </summary>
    public static readonly Coding Duplicate = new Coding
    {
      Code = "duplicate",
      Display = "Duplicate",
      System = "http://hl7.org/fhir/artifactassessment-workflow-status"
    };
    /// <summary>
    /// The necessary changes to the artifact have been published in a new version of the artifact
    /// </summary>
    public static readonly Coding Published = new Coding
    {
      Code = "published",
      Display = "Published",
      System = "http://hl7.org/fhir/artifactassessment-workflow-status"
    };
    /// <summary>
    /// The comment has been resolved and changes are required to address the comment
    /// </summary>
    public static readonly Coding ResolvedChangeRequired = new Coding
    {
      Code = "resolved-change-required",
      Display = "Resolved - Change Required",
      System = "http://hl7.org/fhir/artifactassessment-workflow-status"
    };
    /// <summary>
    /// The comment has been resolved and no changes resulted from the resolution
    /// </summary>
    public static readonly Coding ResolvedNoChange = new Coding
    {
      Code = "resolved-no-change",
      Display = "Resolved - No Change",
      System = "http://hl7.org/fhir/artifactassessment-workflow-status"
    };
    /// <summary>
    /// The comment has been submitted, but the responsible party has not yet been determined, or the responsible party has not yet determined the next steps to be taken.
    /// </summary>
    public static readonly Coding Submitted = new Coding
    {
      Code = "submitted",
      Display = "Submitted",
      System = "http://hl7.org/fhir/artifactassessment-workflow-status"
    };
    /// <summary>
    /// The comment has been triaged, meaning the responsible party has been determined and next steps have been identified to address the comment.
    /// </summary>
    public static readonly Coding Triaged = new Coding
    {
      Code = "triaged",
      Display = "Triaged",
      System = "http://hl7.org/fhir/artifactassessment-workflow-status"
    };
    /// <summary>
    /// The comment is waiting for input from a specific party before next steps can be taken.
    /// </summary>
    public static readonly Coding WaitingForInput = new Coding
    {
      Code = "waiting-for-input",
      Display = "Waiting for Input",
      System = "http://hl7.org/fhir/artifactassessment-workflow-status"
    };

    /// <summary>
    /// Literal for code: Applied
    /// </summary>
    public const string LiteralApplied = "applied";

    /// <summary>
    /// Literal for code: ArtifactassessmentWorkflowStatusApplied
    /// </summary>
    public const string LiteralArtifactassessmentWorkflowStatusApplied = "http://hl7.org/fhir/artifactassessment-workflow-status#applied";

    /// <summary>
    /// Literal for code: Deferred
    /// </summary>
    public const string LiteralDeferred = "deferred";

    /// <summary>
    /// Literal for code: ArtifactassessmentWorkflowStatusDeferred
    /// </summary>
    public const string LiteralArtifactassessmentWorkflowStatusDeferred = "http://hl7.org/fhir/artifactassessment-workflow-status#deferred";

    /// <summary>
    /// Literal for code: Duplicate
    /// </summary>
    public const string LiteralDuplicate = "duplicate";

    /// <summary>
    /// Literal for code: ArtifactassessmentWorkflowStatusDuplicate
    /// </summary>
    public const string LiteralArtifactassessmentWorkflowStatusDuplicate = "http://hl7.org/fhir/artifactassessment-workflow-status#duplicate";

    /// <summary>
    /// Literal for code: Published
    /// </summary>
    public const string LiteralPublished = "published";

    /// <summary>
    /// Literal for code: ArtifactassessmentWorkflowStatusPublished
    /// </summary>
    public const string LiteralArtifactassessmentWorkflowStatusPublished = "http://hl7.org/fhir/artifactassessment-workflow-status#published";

    /// <summary>
    /// Literal for code: ResolvedChangeRequired
    /// </summary>
    public const string LiteralResolvedChangeRequired = "resolved-change-required";

    /// <summary>
    /// Literal for code: ArtifactassessmentWorkflowStatusResolvedChangeRequired
    /// </summary>
    public const string LiteralArtifactassessmentWorkflowStatusResolvedChangeRequired = "http://hl7.org/fhir/artifactassessment-workflow-status#resolved-change-required";

    /// <summary>
    /// Literal for code: ResolvedNoChange
    /// </summary>
    public const string LiteralResolvedNoChange = "resolved-no-change";

    /// <summary>
    /// Literal for code: ArtifactassessmentWorkflowStatusResolvedNoChange
    /// </summary>
    public const string LiteralArtifactassessmentWorkflowStatusResolvedNoChange = "http://hl7.org/fhir/artifactassessment-workflow-status#resolved-no-change";

    /// <summary>
    /// Literal for code: Submitted
    /// </summary>
    public const string LiteralSubmitted = "submitted";

    /// <summary>
    /// Literal for code: ArtifactassessmentWorkflowStatusSubmitted
    /// </summary>
    public const string LiteralArtifactassessmentWorkflowStatusSubmitted = "http://hl7.org/fhir/artifactassessment-workflow-status#submitted";

    /// <summary>
    /// Literal for code: Triaged
    /// </summary>
    public const string LiteralTriaged = "triaged";

    /// <summary>
    /// Literal for code: ArtifactassessmentWorkflowStatusTriaged
    /// </summary>
    public const string LiteralArtifactassessmentWorkflowStatusTriaged = "http://hl7.org/fhir/artifactassessment-workflow-status#triaged";

    /// <summary>
    /// Literal for code: WaitingForInput
    /// </summary>
    public const string LiteralWaitingForInput = "waiting-for-input";

    /// <summary>
    /// Literal for code: ArtifactassessmentWorkflowStatusWaitingForInput
    /// </summary>
    public const string LiteralArtifactassessmentWorkflowStatusWaitingForInput = "http://hl7.org/fhir/artifactassessment-workflow-status#waiting-for-input";

    /// <summary>
    /// Dictionary for looking up ArtifactassessmentWorkflowStatus Codings based on Codes
    /// </summary>
    public static Dictionary<string, Coding> Values = new Dictionary<string, Coding>() {
      { "applied", Applied }, 
      { "http://hl7.org/fhir/artifactassessment-workflow-status#applied", Applied }, 
      { "deferred", Deferred }, 
      { "http://hl7.org/fhir/artifactassessment-workflow-status#deferred", Deferred }, 
      { "duplicate", Duplicate }, 
      { "http://hl7.org/fhir/artifactassessment-workflow-status#duplicate", Duplicate }, 
      { "published", Published }, 
      { "http://hl7.org/fhir/artifactassessment-workflow-status#published", Published }, 
      { "resolved-change-required", ResolvedChangeRequired }, 
      { "http://hl7.org/fhir/artifactassessment-workflow-status#resolved-change-required", ResolvedChangeRequired }, 
      { "resolved-no-change", ResolvedNoChange }, 
      { "http://hl7.org/fhir/artifactassessment-workflow-status#resolved-no-change", ResolvedNoChange }, 
      { "submitted", Submitted }, 
      { "http://hl7.org/fhir/artifactassessment-workflow-status#submitted", Submitted }, 
      { "triaged", Triaged }, 
      { "http://hl7.org/fhir/artifactassessment-workflow-status#triaged", Triaged }, 
      { "waiting-for-input", WaitingForInput }, 
      { "http://hl7.org/fhir/artifactassessment-workflow-status#waiting-for-input", WaitingForInput }, 
    };
  };
}
