// <auto-generated />
// Built from: hl7.fhir.r5.core version: 5.0.0-snapshot1
  // Option: "NAMESPACE" = "fhirCsR5"

using fhirCsR5.Models;

namespace fhirCsR5.ValueSets
{
  /// <summary>
  /// The event used as a base point (reference point) in time.
  /// </summary>
  public static class EvidenceVariableEventCodes
  {
    /// <summary>
    /// The time of admission to the hospital
    /// </summary>
    public static readonly Coding HospitalAdmission = new Coding
    {
      Code = "hospital-admission",
      Display = "Hospital Admission",
      System = "http://hl7.org/fhir/evidence-variable-event"
    };
    /// <summary>
    /// The time of discharge from the hospital
    /// </summary>
    public static readonly Coding HospitalDischarge = new Coding
    {
      Code = "hospital-discharge",
      Display = "Hospital Discharge",
      System = "http://hl7.org/fhir/evidence-variable-event"
    };
    /// <summary>
    /// The time of surgery
    /// </summary>
    public static readonly Coding OperativeProcedure = new Coding
    {
      Code = "operative-procedure",
      Display = "Operative Procedure",
      System = "http://hl7.org/fhir/evidence-variable-event"
    };
    /// <summary>
    /// The time of enrollment for the study participant
    /// </summary>
    public static readonly Coding StudyStart = new Coding
    {
      Code = "study-start",
      Display = "Study Start",
      System = "http://hl7.org/fhir/evidence-variable-event"
    };

    /// <summary>
    /// Literal for code: HospitalAdmission
    /// </summary>
    public const string LiteralHospitalAdmission = "hospital-admission";

    /// <summary>
    /// Literal for code: EvidenceVariableEventHospitalAdmission
    /// </summary>
    public const string LiteralEvidenceVariableEventHospitalAdmission = "http://hl7.org/fhir/evidence-variable-event#hospital-admission";

    /// <summary>
    /// Literal for code: HospitalDischarge
    /// </summary>
    public const string LiteralHospitalDischarge = "hospital-discharge";

    /// <summary>
    /// Literal for code: EvidenceVariableEventHospitalDischarge
    /// </summary>
    public const string LiteralEvidenceVariableEventHospitalDischarge = "http://hl7.org/fhir/evidence-variable-event#hospital-discharge";

    /// <summary>
    /// Literal for code: OperativeProcedure
    /// </summary>
    public const string LiteralOperativeProcedure = "operative-procedure";

    /// <summary>
    /// Literal for code: EvidenceVariableEventOperativeProcedure
    /// </summary>
    public const string LiteralEvidenceVariableEventOperativeProcedure = "http://hl7.org/fhir/evidence-variable-event#operative-procedure";

    /// <summary>
    /// Literal for code: StudyStart
    /// </summary>
    public const string LiteralStudyStart = "study-start";

    /// <summary>
    /// Literal for code: EvidenceVariableEventStudyStart
    /// </summary>
    public const string LiteralEvidenceVariableEventStudyStart = "http://hl7.org/fhir/evidence-variable-event#study-start";

    /// <summary>
    /// Dictionary for looking up EvidenceVariableEvent Codings based on Codes
    /// </summary>
    public static Dictionary<string, Coding> Values = new Dictionary<string, Coding>() {
      { "hospital-admission", HospitalAdmission }, 
      { "http://hl7.org/fhir/evidence-variable-event#hospital-admission", HospitalAdmission }, 
      { "hospital-discharge", HospitalDischarge }, 
      { "http://hl7.org/fhir/evidence-variable-event#hospital-discharge", HospitalDischarge }, 
      { "operative-procedure", OperativeProcedure }, 
      { "http://hl7.org/fhir/evidence-variable-event#operative-procedure", OperativeProcedure }, 
      { "study-start", StudyStart }, 
      { "http://hl7.org/fhir/evidence-variable-event#study-start", StudyStart }, 
    };
  };
}
