// <auto-generated />
// Built from: hl7.fhir.r5.core version: 5.0.0-snapshot1
  // Option: "NAMESPACE" = "fhirCsR5"

using fhirCsR5.Models;

namespace fhirCsR5.ValueSets
{
  /// <summary>
  /// The media type of the expression language.
  /// </summary>
  public static class ExpressionLanguageCodes
  {
    /// <summary>
    /// CQL
    /// </summary>
    public static readonly Coding CQL = new Coding
    {
      Code = "text/cql",
      Display = "CQL",
      System = "urn:ietf:bcp:13"
    };
    /// <summary>
    /// CQL Identifier
    /// </summary>
    public static readonly Coding CQLIdentifier = new Coding
    {
      Code = "text/cql.identifier",
      Display = "CQL Identifier",
      System = "urn:ietf:bcp:13"
    };
    /// <summary>
    /// FHIRPath
    /// </summary>
    public static readonly Coding FHIRPath = new Coding
    {
      Code = "text/fhirpath",
      Display = "FHIRPath",
      System = "urn:ietf:bcp:13"
    };
    /// <summary>
    /// FHIR Query
    /// </summary>
    public static readonly Coding FHIRQuery = new Coding
    {
      Code = "text/x-fhir-query",
      Display = "FHIR Query",
      System = "urn:ietf:bcp:13"
    };

    /// <summary>
    /// Literal for code: CQL
    /// </summary>
    public const string LiteralCQL = "text/cql";

    /// <summary>
    /// Literal for code: NONECQL
    /// </summary>
    public const string LiteralNONECQL = "urn:ietf:bcp:13#text/cql";

    /// <summary>
    /// Literal for code: CQLIdentifier
    /// </summary>
    public const string LiteralCQLIdentifier = "text/cql.identifier";

    /// <summary>
    /// Literal for code: NONECQLIdentifier
    /// </summary>
    public const string LiteralNONECQLIdentifier = "urn:ietf:bcp:13#text/cql.identifier";

    /// <summary>
    /// Literal for code: FHIRPath
    /// </summary>
    public const string LiteralFHIRPath = "text/fhirpath";

    /// <summary>
    /// Literal for code: NONEFHIRPath
    /// </summary>
    public const string LiteralNONEFHIRPath = "urn:ietf:bcp:13#text/fhirpath";

    /// <summary>
    /// Literal for code: FHIRQuery
    /// </summary>
    public const string LiteralFHIRQuery = "text/x-fhir-query";

    /// <summary>
    /// Literal for code: NONEFHIRQuery
    /// </summary>
    public const string LiteralNONEFHIRQuery = "urn:ietf:bcp:13#text/x-fhir-query";

    /// <summary>
    /// Dictionary for looking up ExpressionLanguage Codings based on Codes
    /// </summary>
    public static Dictionary<string, Coding> Values = new Dictionary<string, Coding>() {
      { "text/cql", CQL }, 
      { "urn:ietf:bcp:13#text/cql", CQL }, 
      { "text/cql.identifier", CQLIdentifier }, 
      { "urn:ietf:bcp:13#text/cql.identifier", CQLIdentifier }, 
      { "text/fhirpath", FHIRPath }, 
      { "urn:ietf:bcp:13#text/fhirpath", FHIRPath }, 
      { "text/x-fhir-query", FHIRQuery }, 
      { "urn:ietf:bcp:13#text/x-fhir-query", FHIRQuery }, 
    };
  };
}
