// <auto-generated />
// Built from: hl7.fhir.r2.core version: 1.0.2
  // Option: "NAMESPACE" = "fhirCsR2"

using fhirCsR2.Models;

namespace fhirCsR2.ValueSets
{
  /// <summary>
  /// Real world event that the relating to the schedule.
  /// </summary>
  public static class EventTimingCodes
  {
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding AC = new Coding
    {
      Code = "AC",
      System = "http://hl7.org/fhir/v3/TimingEvent"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ACD = new Coding
    {
      Code = "ACD",
      System = "http://hl7.org/fhir/v3/TimingEvent"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ACM = new Coding
    {
      Code = "ACM",
      System = "http://hl7.org/fhir/v3/TimingEvent"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ACV = new Coding
    {
      Code = "ACV",
      System = "http://hl7.org/fhir/v3/TimingEvent"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding C = new Coding
    {
      Code = "C",
      System = "http://hl7.org/fhir/v3/TimingEvent"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding CD = new Coding
    {
      Code = "CD",
      System = "http://hl7.org/fhir/v3/TimingEvent"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding CM = new Coding
    {
      Code = "CM",
      System = "http://hl7.org/fhir/v3/TimingEvent"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding CV = new Coding
    {
      Code = "CV",
      System = "http://hl7.org/fhir/v3/TimingEvent"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HS = new Coding
    {
      Code = "HS",
      System = "http://hl7.org/fhir/v3/TimingEvent"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PC = new Coding
    {
      Code = "PC",
      System = "http://hl7.org/fhir/v3/TimingEvent"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PCD = new Coding
    {
      Code = "PCD",
      System = "http://hl7.org/fhir/v3/TimingEvent"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PCM = new Coding
    {
      Code = "PCM",
      System = "http://hl7.org/fhir/v3/TimingEvent"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PCV = new Coding
    {
      Code = "PCV",
      System = "http://hl7.org/fhir/v3/TimingEvent"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding WAKE = new Coding
    {
      Code = "WAKE",
      System = "http://hl7.org/fhir/v3/TimingEvent"
    };

    /// <summary>
    /// Literal for code: AC
    /// </summary>
    public const string LiteralAC = "AC";

    /// <summary>
    /// Literal for code: ACD
    /// </summary>
    public const string LiteralACD = "ACD";

    /// <summary>
    /// Literal for code: ACM
    /// </summary>
    public const string LiteralACM = "ACM";

    /// <summary>
    /// Literal for code: ACV
    /// </summary>
    public const string LiteralACV = "ACV";

    /// <summary>
    /// Literal for code: C
    /// </summary>
    public const string LiteralC = "C";

    /// <summary>
    /// Literal for code: CD
    /// </summary>
    public const string LiteralCD = "CD";

    /// <summary>
    /// Literal for code: CM
    /// </summary>
    public const string LiteralCM = "CM";

    /// <summary>
    /// Literal for code: CV
    /// </summary>
    public const string LiteralCV = "CV";

    /// <summary>
    /// Literal for code: HS
    /// </summary>
    public const string LiteralHS = "HS";

    /// <summary>
    /// Literal for code: PC
    /// </summary>
    public const string LiteralPC = "PC";

    /// <summary>
    /// Literal for code: PCD
    /// </summary>
    public const string LiteralPCD = "PCD";

    /// <summary>
    /// Literal for code: PCM
    /// </summary>
    public const string LiteralPCM = "PCM";

    /// <summary>
    /// Literal for code: PCV
    /// </summary>
    public const string LiteralPCV = "PCV";

    /// <summary>
    /// Literal for code: WAKE
    /// </summary>
    public const string LiteralWAKE = "WAKE";
  };
}
