// <auto-generated />
// Built from: hl7.fhir.r3.core version: 3.0.2
  // Option: "NAMESPACE" = "fhirCsR3"

using fhirCsR3.Models;

namespace fhirCsR3.ValueSets
{
  /// <summary>
  /// This value set includes sample Information Category codes.
  /// </summary>
  public static class ClaimInformationcategoryCodes
  {
    /// <summary>
    /// Materials attached such as images, documents and resources.
    /// </summary>
    public static readonly Coding Attachment = new Coding
    {
      Code = "attachment",
      Display = "Attachment",
      System = "http://hl7.org/fhir/claiminformationcategory"
    };
    /// <summary>
    /// Discharge status and discharge to locations.
    /// </summary>
    public static readonly Coding Discharge = new Coding
    {
      Code = "discharge",
      Display = "Discharge",
      System = "http://hl7.org/fhir/claiminformationcategory"
    };
    /// <summary>
    /// Insurance policy exceptions.
    /// </summary>
    public static readonly Coding Exception = new Coding
    {
      Code = "exception",
      Display = "Exception",
      System = "http://hl7.org/fhir/claiminformationcategory"
    };
    /// <summary>
    /// Codes conveying additional situation and condition information.
    /// </summary>
    public static readonly Coding Information = new Coding
    {
      Code = "info",
      Display = "Information",
      System = "http://hl7.org/fhir/claiminformationcategory"
    };
    /// <summary>
    /// Materials being forwarded, eg. Models, molds, images, documents.
    /// </summary>
    public static readonly Coding MaterialsForwarded = new Coding
    {
      Code = "material",
      Display = "Materials Forwarded",
      System = "http://hl7.org/fhir/claiminformationcategory"
    };
    /// <summary>
    /// Teeth which are missing for any reason, for example: prior extraction, never developed.
    /// </summary>
    public static readonly Coding MissingTooth = new Coding
    {
      Code = "missingtooth",
      Display = "Missing Tooth",
      System = "http://hl7.org/fhir/claiminformationcategory"
    };
    /// <summary>
    /// Period, start or end dates of aspects of the Condition.
    /// </summary>
    public static readonly Coding Onset = new Coding
    {
      Code = "onset",
      Display = "Onset",
      System = "http://hl7.org/fhir/claiminformationcategory"
    };
    /// <summary>
    /// Other information identified by the type.system.
    /// </summary>
    public static readonly Coding Other = new Coding
    {
      Code = "other",
      Display = "Other",
      System = "http://hl7.org/fhir/claiminformationcategory"
    };
    /// <summary>
    /// The type of prosthesis and date of supply if a previously supplied prosthesis.
    /// </summary>
    public static readonly Coding Prosthesis = new Coding
    {
      Code = "prosthesis",
      Display = "Prosthesis",
      System = "http://hl7.org/fhir/claiminformationcategory"
    };
    /// <summary>
    /// Nature and date of the related event eg. Last exam, service, Xray etc.
    /// </summary>
    public static readonly Coding RelatedServices = new Coding
    {
      Code = "related",
      Display = "Related Services",
      System = "http://hl7.org/fhir/claiminformationcategory"
    };

    /// <summary>
    /// Literal for code: Attachment
    /// </summary>
    public const string LiteralAttachment = "attachment";

    /// <summary>
    /// Literal for code: Discharge
    /// </summary>
    public const string LiteralDischarge = "discharge";

    /// <summary>
    /// Literal for code: Exception
    /// </summary>
    public const string LiteralException = "exception";

    /// <summary>
    /// Literal for code: Information
    /// </summary>
    public const string LiteralInformation = "info";

    /// <summary>
    /// Literal for code: MaterialsForwarded
    /// </summary>
    public const string LiteralMaterialsForwarded = "material";

    /// <summary>
    /// Literal for code: MissingTooth
    /// </summary>
    public const string LiteralMissingTooth = "missingtooth";

    /// <summary>
    /// Literal for code: Onset
    /// </summary>
    public const string LiteralOnset = "onset";

    /// <summary>
    /// Literal for code: Other
    /// </summary>
    public const string LiteralOther = "other";

    /// <summary>
    /// Literal for code: Prosthesis
    /// </summary>
    public const string LiteralProsthesis = "prosthesis";

    /// <summary>
    /// Literal for code: RelatedServices
    /// </summary>
    public const string LiteralRelatedServices = "related";
  };
}
