// <auto-generated />
// Built from: hl7.fhir.r3.core version: 3.0.2
  // Option: "NAMESPACE" = "fhirCsR3"

using fhirCsR3.Models;

namespace fhirCsR3.ValueSets
{
  /// <summary>
  /// This value set includes sample Contract Action codes.
  /// </summary>
  public static class ContractActionCodes
  {
    /// <summary>
    /// Definition for Action A
    /// </summary>
    public static readonly Coding ActionA = new Coding
    {
      Code = "action-a",
      Display = "Action A",
      System = "http://www.hl7.org/fhir/contractaction"
    };
    /// <summary>
    /// Definition for Action B
    /// </summary>
    public static readonly Coding ActionB = new Coding
    {
      Code = "action-b",
      Display = "Action B",
      System = "http://www.hl7.org/fhir/contractaction"
    };

    /// <summary>
    /// Literal for code: ActionA
    /// </summary>
    public const string LiteralActionA = "action-a";

    /// <summary>
    /// Literal for code: ContractActionActionA
    /// </summary>
    public const string LiteralContractActionActionA = "http://www.hl7.org/fhir/contractaction#action-a";

    /// <summary>
    /// Literal for code: ActionB
    /// </summary>
    public const string LiteralActionB = "action-b";

    /// <summary>
    /// Literal for code: ContractActionActionB
    /// </summary>
    public const string LiteralContractActionActionB = "http://www.hl7.org/fhir/contractaction#action-b";

    /// <summary>
    /// Dictionary for looking up ContractAction Codings based on Codes
    /// </summary>
    public static Dictionary<string, Coding> Values = new Dictionary<string, Coding>() {
      { "action-a", ActionA }, 
      { "http://www.hl7.org/fhir/contractaction#action-a", ActionA }, 
      { "action-b", ActionB }, 
      { "http://www.hl7.org/fhir/contractaction#action-b", ActionB }, 
    };
  };
}
