// <auto-generated />
// Built from: hl7.fhir.r3.core version: 3.0.2
  // Option: "NAMESPACE" = "fhirCsR3"

using fhirCsR3.Models;

namespace fhirCsR3.ValueSets
{
  /// <summary>
  /// Example list of general categories for flagged issues. (Not complete or necessarily appropriate.)
  /// </summary>
  public static class FlagCategoryCodes
  {
    /// <summary>
    /// Flags related to administrative and financial processes.
    /// </summary>
    public static readonly Coding Administrative = new Coding
    {
      Code = "admin",
      Display = "Administrative",
      System = "http://hl7.org/fhir/flag-category"
    };
    /// <summary>
    /// Flags related to coming into contact with the patient.
    /// </summary>
    public static readonly Coding SubjectContact = new Coding
    {
      Code = "contact",
      Display = "Subject contact",
      System = "http://hl7.org/fhir/flag-category"
    };
    /// <summary>
    /// Flags related to the subject's dietary needs.
    /// </summary>
    public static readonly Coding Diet = new Coding
    {
      Code = "diet",
      Display = "Diet",
      System = "http://hl7.org/fhir/flag-category"
    };
    /// <summary>
    /// Flags related to the patient's medications.
    /// </summary>
    public static readonly Coding Drug = new Coding
    {
      Code = "drug",
      Display = "Drug",
      System = "http://hl7.org/fhir/flag-category"
    };
    /// <summary>
    /// Flags related to performing laboratory tests and related processes (e.g. phlebotomy).
    /// </summary>
    public static readonly Coding Lab = new Coding
    {
      Code = "lab",
      Display = "Lab",
      System = "http://hl7.org/fhir/flag-category"
    };

    /// <summary>
    /// Literal for code: Administrative
    /// </summary>
    public const string LiteralAdministrative = "admin";

    /// <summary>
    /// Literal for code: FlagCategoryAdministrative
    /// </summary>
    public const string LiteralFlagCategoryAdministrative = "http://hl7.org/fhir/flag-category#admin";

    /// <summary>
    /// Literal for code: SubjectContact
    /// </summary>
    public const string LiteralSubjectContact = "contact";

    /// <summary>
    /// Literal for code: FlagCategorySubjectContact
    /// </summary>
    public const string LiteralFlagCategorySubjectContact = "http://hl7.org/fhir/flag-category#contact";

    /// <summary>
    /// Literal for code: Diet
    /// </summary>
    public const string LiteralDiet = "diet";

    /// <summary>
    /// Literal for code: FlagCategoryDiet
    /// </summary>
    public const string LiteralFlagCategoryDiet = "http://hl7.org/fhir/flag-category#diet";

    /// <summary>
    /// Literal for code: Drug
    /// </summary>
    public const string LiteralDrug = "drug";

    /// <summary>
    /// Literal for code: FlagCategoryDrug
    /// </summary>
    public const string LiteralFlagCategoryDrug = "http://hl7.org/fhir/flag-category#drug";

    /// <summary>
    /// Literal for code: Lab
    /// </summary>
    public const string LiteralLab = "lab";

    /// <summary>
    /// Literal for code: FlagCategoryLab
    /// </summary>
    public const string LiteralFlagCategoryLab = "http://hl7.org/fhir/flag-category#lab";

    /// <summary>
    /// Dictionary for looking up FlagCategory Codings based on Codes
    /// </summary>
    public static Dictionary<string, Coding> Values = new Dictionary<string, Coding>() {
      { "admin", Administrative }, 
      { "http://hl7.org/fhir/flag-category#admin", Administrative }, 
      { "contact", SubjectContact }, 
      { "http://hl7.org/fhir/flag-category#contact", SubjectContact }, 
      { "diet", Diet }, 
      { "http://hl7.org/fhir/flag-category#diet", Diet }, 
      { "drug", Drug }, 
      { "http://hl7.org/fhir/flag-category#drug", Drug }, 
      { "lab", Lab }, 
      { "http://hl7.org/fhir/flag-category#lab", Lab }, 
    };
  };
}
