// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.3.0-snapshot1
  // Option: "NAMESPACE" = "fhirCsR4B"

using fhirCsR4B.Models;

namespace fhirCsR4B.ValueSets
{
  /// <summary>
  /// This value set includes Claim Type codes.
  /// </summary>
  public static class ClaimTypeCodes
  {
    /// <summary>
    /// Hospital, clinic and typically inpatient claims.
    /// </summary>
    public static readonly Coding Institutional = new Coding
    {
      Code = "institutional",
      Display = "Institutional",
      System = "http://terminology.hl7.org/CodeSystem/claim-type"
    };
    /// <summary>
    /// Dental, Denture and Hygiene claims.
    /// </summary>
    public static readonly Coding Oral = new Coding
    {
      Code = "oral",
      Display = "Oral",
      System = "http://terminology.hl7.org/CodeSystem/claim-type"
    };
    /// <summary>
    /// Pharmacy claims for goods and services.
    /// </summary>
    public static readonly Coding Pharmacy = new Coding
    {
      Code = "pharmacy",
      Display = "Pharmacy",
      System = "http://terminology.hl7.org/CodeSystem/claim-type"
    };
    /// <summary>
    /// Typically, outpatient claims from Physician, Psychological, Chiropractor, Physiotherapy, Speech Pathology, rehabilitative, consulting.
    /// </summary>
    public static readonly Coding Professional = new Coding
    {
      Code = "professional",
      Display = "Professional",
      System = "http://terminology.hl7.org/CodeSystem/claim-type"
    };
    /// <summary>
    /// Vision claims for professional services and products such as glasses and contact lenses.
    /// </summary>
    public static readonly Coding Vision = new Coding
    {
      Code = "vision",
      Display = "Vision",
      System = "http://terminology.hl7.org/CodeSystem/claim-type"
    };

    /// <summary>
    /// Literal for code: Institutional
    /// </summary>
    public const string LiteralInstitutional = "institutional";

    /// <summary>
    /// Literal for code: ClaimTypeInstitutional
    /// </summary>
    public const string LiteralClaimTypeInstitutional = "http://terminology.hl7.org/CodeSystem/claim-type#institutional";

    /// <summary>
    /// Literal for code: Oral
    /// </summary>
    public const string LiteralOral = "oral";

    /// <summary>
    /// Literal for code: ClaimTypeOral
    /// </summary>
    public const string LiteralClaimTypeOral = "http://terminology.hl7.org/CodeSystem/claim-type#oral";

    /// <summary>
    /// Literal for code: Pharmacy
    /// </summary>
    public const string LiteralPharmacy = "pharmacy";

    /// <summary>
    /// Literal for code: ClaimTypePharmacy
    /// </summary>
    public const string LiteralClaimTypePharmacy = "http://terminology.hl7.org/CodeSystem/claim-type#pharmacy";

    /// <summary>
    /// Literal for code: Professional
    /// </summary>
    public const string LiteralProfessional = "professional";

    /// <summary>
    /// Literal for code: ClaimTypeProfessional
    /// </summary>
    public const string LiteralClaimTypeProfessional = "http://terminology.hl7.org/CodeSystem/claim-type#professional";

    /// <summary>
    /// Literal for code: Vision
    /// </summary>
    public const string LiteralVision = "vision";

    /// <summary>
    /// Literal for code: ClaimTypeVision
    /// </summary>
    public const string LiteralClaimTypeVision = "http://terminology.hl7.org/CodeSystem/claim-type#vision";

    /// <summary>
    /// Dictionary for looking up ClaimType Codings based on Codes
    /// </summary>
    public static Dictionary<string, Coding> Values = new Dictionary<string, Coding>() {
      { "institutional", Institutional }, 
      { "http://terminology.hl7.org/CodeSystem/claim-type#institutional", Institutional }, 
      { "oral", Oral }, 
      { "http://terminology.hl7.org/CodeSystem/claim-type#oral", Oral }, 
      { "pharmacy", Pharmacy }, 
      { "http://terminology.hl7.org/CodeSystem/claim-type#pharmacy", Pharmacy }, 
      { "professional", Professional }, 
      { "http://terminology.hl7.org/CodeSystem/claim-type#professional", Professional }, 
      { "vision", Vision }, 
      { "http://terminology.hl7.org/CodeSystem/claim-type#vision", Vision }, 
    };
  };
}
