// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.3.0-snapshot1
  // Option: "NAMESPACE" = "fhirCsR4B"

using fhirCsR4B.Models;

namespace fhirCsR4B.ValueSets
{
  /// <summary>
  /// This value set includes examples of Benefit Category codes.
  /// </summary>
  public static class ExBenefitcategoryCodes
  {
    /// <summary>
    /// Medical Care.
    /// </summary>
    public static readonly Coding MedicalCare = new Coding
    {
      Code = "1",
      Display = "Medical Care",
      System = "http://terminology.hl7.org/CodeSystem/ex-benefitcategory"
    };
    /// <summary>
    /// Renal Supplies excluding Dialysis.
    /// </summary>
    public static readonly Coding RenalSupplies = new Coding
    {
      Code = "14",
      Display = "Renal Supplies",
      System = "http://terminology.hl7.org/CodeSystem/ex-benefitcategory"
    };
    /// <summary>
    /// Surgical.
    /// </summary>
    public static readonly Coding Surgical = new Coding
    {
      Code = "2",
      Display = "Surgical",
      System = "http://terminology.hl7.org/CodeSystem/ex-benefitcategory"
    };
    /// <summary>
    /// Diagnostic Dental.
    /// </summary>
    public static readonly Coding DiagnosticDental = new Coding
    {
      Code = "23",
      Display = "Diagnostic Dental",
      System = "http://terminology.hl7.org/CodeSystem/ex-benefitcategory"
    };
    /// <summary>
    /// Periodontics.
    /// </summary>
    public static readonly Coding Periodontics = new Coding
    {
      Code = "24",
      Display = "Periodontics",
      System = "http://terminology.hl7.org/CodeSystem/ex-benefitcategory"
    };
    /// <summary>
    /// Restorative.
    /// </summary>
    public static readonly Coding Restorative = new Coding
    {
      Code = "25",
      Display = "Restorative",
      System = "http://terminology.hl7.org/CodeSystem/ex-benefitcategory"
    };
    /// <summary>
    /// Endodontics.
    /// </summary>
    public static readonly Coding Endodontics = new Coding
    {
      Code = "26",
      Display = "Endodontics",
      System = "http://terminology.hl7.org/CodeSystem/ex-benefitcategory"
    };
    /// <summary>
    /// Maxillofacial Prosthetics.
    /// </summary>
    public static readonly Coding MaxillofacialProsthetics = new Coding
    {
      Code = "27",
      Display = "Maxillofacial Prosthetics",
      System = "http://terminology.hl7.org/CodeSystem/ex-benefitcategory"
    };
    /// <summary>
    /// Adjunctive Dental Services.
    /// </summary>
    public static readonly Coding AdjunctiveDentalServices = new Coding
    {
      Code = "28",
      Display = "Adjunctive Dental Services",
      System = "http://terminology.hl7.org/CodeSystem/ex-benefitcategory"
    };
    /// <summary>
    /// Consultation.
    /// </summary>
    public static readonly Coding Consultation = new Coding
    {
      Code = "3",
      Display = "Consultation",
      System = "http://terminology.hl7.org/CodeSystem/ex-benefitcategory"
    };
    /// <summary>
    /// Health Benefit Plan Coverage.
    /// </summary>
    public static readonly Coding HealthBenefitPlanCoverage = new Coding
    {
      Code = "30",
      Display = "Health Benefit Plan Coverage",
      System = "http://terminology.hl7.org/CodeSystem/ex-benefitcategory"
    };
    /// <summary>
    /// Dental Care.
    /// </summary>
    public static readonly Coding DentalCare = new Coding
    {
      Code = "35",
      Display = "Dental Care",
      System = "http://terminology.hl7.org/CodeSystem/ex-benefitcategory"
    };
    /// <summary>
    /// Dental Crowns.
    /// </summary>
    public static readonly Coding DentalCrowns = new Coding
    {
      Code = "36",
      Display = "Dental Crowns",
      System = "http://terminology.hl7.org/CodeSystem/ex-benefitcategory"
    };
    /// <summary>
    /// Dental Accident.
    /// </summary>
    public static readonly Coding DentalAccident = new Coding
    {
      Code = "37",
      Display = "Dental Accident",
      System = "http://terminology.hl7.org/CodeSystem/ex-benefitcategory"
    };
    /// <summary>
    /// Diagnostic XRay.
    /// </summary>
    public static readonly Coding DiagnosticXRay = new Coding
    {
      Code = "4",
      Display = "Diagnostic XRay",
      System = "http://terminology.hl7.org/CodeSystem/ex-benefitcategory"
    };
    /// <summary>
    /// Hospital Room and Board.
    /// </summary>
    public static readonly Coding HospitalRoomAndBoard = new Coding
    {
      Code = "49",
      Display = "Hospital Room and Board",
      System = "http://terminology.hl7.org/CodeSystem/ex-benefitcategory"
    };
    /// <summary>
    /// Diagnostic Lab.
    /// </summary>
    public static readonly Coding DiagnosticLab = new Coding
    {
      Code = "5",
      Display = "Diagnostic Lab",
      System = "http://terminology.hl7.org/CodeSystem/ex-benefitcategory"
    };
    /// <summary>
    /// Major Medical.
    /// </summary>
    public static readonly Coding MajorMedical = new Coding
    {
      Code = "55",
      Display = "Major Medical",
      System = "http://terminology.hl7.org/CodeSystem/ex-benefitcategory"
    };
    /// <summary>
    /// Medically Related Transportation.
    /// </summary>
    public static readonly Coding MedicallyRelatedTransportation = new Coding
    {
      Code = "56",
      Display = "Medically Related Transportation",
      System = "http://terminology.hl7.org/CodeSystem/ex-benefitcategory"
    };
    /// <summary>
    /// In-vitro Fertilization.
    /// </summary>
    public static readonly Coding InVitroFertilization = new Coding
    {
      Code = "61",
      Display = "In-vitro Fertilization",
      System = "http://terminology.hl7.org/CodeSystem/ex-benefitcategory"
    };
    /// <summary>
    /// MRI Scan.
    /// </summary>
    public static readonly Coding MRIScan = new Coding
    {
      Code = "62",
      Display = "MRI Scan",
      System = "http://terminology.hl7.org/CodeSystem/ex-benefitcategory"
    };
    /// <summary>
    /// Donor Procedures such as organ harvest.
    /// </summary>
    public static readonly Coding DonorProcedures = new Coding
    {
      Code = "63",
      Display = "Donor Procedures",
      System = "http://terminology.hl7.org/CodeSystem/ex-benefitcategory"
    };
    /// <summary>
    /// Maternity.
    /// </summary>
    public static readonly Coding Maternity = new Coding
    {
      Code = "69",
      Display = "Maternity",
      System = "http://terminology.hl7.org/CodeSystem/ex-benefitcategory"
    };
    /// <summary>
    /// Renal dialysis.
    /// </summary>
    public static readonly Coding RenalDialysis = new Coding
    {
      Code = "76",
      Display = "Renal Dialysis",
      System = "http://terminology.hl7.org/CodeSystem/ex-benefitcategory"
    };
    /// <summary>
    /// Medical Coverage.
    /// </summary>
    public static readonly Coding MedicalCoverage = new Coding
    {
      Code = "F1",
      Display = "Medical Coverage",
      System = "http://terminology.hl7.org/CodeSystem/ex-benefitcategory"
    };
    /// <summary>
    /// Dental Coverage.
    /// </summary>
    public static readonly Coding DentalCoverage = new Coding
    {
      Code = "F3",
      Display = "Dental Coverage",
      System = "http://terminology.hl7.org/CodeSystem/ex-benefitcategory"
    };
    /// <summary>
    /// Hearing Coverage.
    /// </summary>
    public static readonly Coding HearingCoverage = new Coding
    {
      Code = "F4",
      Display = "Hearing Coverage",
      System = "http://terminology.hl7.org/CodeSystem/ex-benefitcategory"
    };
    /// <summary>
    /// Vision Coverage.
    /// </summary>
    public static readonly Coding VisionCoverage = new Coding
    {
      Code = "F6",
      Display = "Vision Coverage",
      System = "http://terminology.hl7.org/CodeSystem/ex-benefitcategory"
    };

    /// <summary>
    /// Literal for code: MedicalCare
    /// </summary>
    public const string LiteralMedicalCare = "1";

    /// <summary>
    /// Literal for code: RenalSupplies
    /// </summary>
    public const string LiteralRenalSupplies = "14";

    /// <summary>
    /// Literal for code: Surgical
    /// </summary>
    public const string LiteralSurgical = "2";

    /// <summary>
    /// Literal for code: DiagnosticDental
    /// </summary>
    public const string LiteralDiagnosticDental = "23";

    /// <summary>
    /// Literal for code: Periodontics
    /// </summary>
    public const string LiteralPeriodontics = "24";

    /// <summary>
    /// Literal for code: Restorative
    /// </summary>
    public const string LiteralRestorative = "25";

    /// <summary>
    /// Literal for code: Endodontics
    /// </summary>
    public const string LiteralEndodontics = "26";

    /// <summary>
    /// Literal for code: MaxillofacialProsthetics
    /// </summary>
    public const string LiteralMaxillofacialProsthetics = "27";

    /// <summary>
    /// Literal for code: AdjunctiveDentalServices
    /// </summary>
    public const string LiteralAdjunctiveDentalServices = "28";

    /// <summary>
    /// Literal for code: Consultation
    /// </summary>
    public const string LiteralConsultation = "3";

    /// <summary>
    /// Literal for code: HealthBenefitPlanCoverage
    /// </summary>
    public const string LiteralHealthBenefitPlanCoverage = "30";

    /// <summary>
    /// Literal for code: DentalCare
    /// </summary>
    public const string LiteralDentalCare = "35";

    /// <summary>
    /// Literal for code: DentalCrowns
    /// </summary>
    public const string LiteralDentalCrowns = "36";

    /// <summary>
    /// Literal for code: DentalAccident
    /// </summary>
    public const string LiteralDentalAccident = "37";

    /// <summary>
    /// Literal for code: DiagnosticXRay
    /// </summary>
    public const string LiteralDiagnosticXRay = "4";

    /// <summary>
    /// Literal for code: HospitalRoomAndBoard
    /// </summary>
    public const string LiteralHospitalRoomAndBoard = "49";

    /// <summary>
    /// Literal for code: DiagnosticLab
    /// </summary>
    public const string LiteralDiagnosticLab = "5";

    /// <summary>
    /// Literal for code: MajorMedical
    /// </summary>
    public const string LiteralMajorMedical = "55";

    /// <summary>
    /// Literal for code: MedicallyRelatedTransportation
    /// </summary>
    public const string LiteralMedicallyRelatedTransportation = "56";

    /// <summary>
    /// Literal for code: InVitroFertilization
    /// </summary>
    public const string LiteralInVitroFertilization = "61";

    /// <summary>
    /// Literal for code: MRIScan
    /// </summary>
    public const string LiteralMRIScan = "62";

    /// <summary>
    /// Literal for code: DonorProcedures
    /// </summary>
    public const string LiteralDonorProcedures = "63";

    /// <summary>
    /// Literal for code: Maternity
    /// </summary>
    public const string LiteralMaternity = "69";

    /// <summary>
    /// Literal for code: RenalDialysis
    /// </summary>
    public const string LiteralRenalDialysis = "76";

    /// <summary>
    /// Literal for code: MedicalCoverage
    /// </summary>
    public const string LiteralMedicalCoverage = "F1";

    /// <summary>
    /// Literal for code: DentalCoverage
    /// </summary>
    public const string LiteralDentalCoverage = "F3";

    /// <summary>
    /// Literal for code: HearingCoverage
    /// </summary>
    public const string LiteralHearingCoverage = "F4";

    /// <summary>
    /// Literal for code: VisionCoverage
    /// </summary>
    public const string LiteralVisionCoverage = "F6";
  };
}
