// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.3.0-snapshot1
  // Option: "NAMESPACE" = "fhirCsR4B"

using fhirCsR4B.Models;

namespace fhirCsR4B.ValueSets
{
  /// <summary>
  /// Example Message Reasons. These are the set of codes that might be used an updating an encounter using admin-update.
  /// </summary>
  public static class MessageReasonEncounterCodes
  {
    /// <summary>
    /// The patient has temporarily left the institution.
    /// </summary>
    public static readonly Coding Absent = new Coding
    {
      Code = "absent",
      Display = "Absent",
      System = "http://terminology.hl7.org/CodeSystem/message-reasons-encounter"
    };
    /// <summary>
    /// The patient has been admitted.
    /// </summary>
    public static readonly Coding Admit = new Coding
    {
      Code = "admit",
      Display = "Admit",
      System = "http://terminology.hl7.org/CodeSystem/message-reasons-encounter"
    };
    /// <summary>
    /// The patient has been discharged.
    /// </summary>
    public static readonly Coding Discharge = new Coding
    {
      Code = "discharge",
      Display = "Discharge",
      System = "http://terminology.hl7.org/CodeSystem/message-reasons-encounter"
    };
    /// <summary>
    /// Encounter details have been updated (e.g. to correct a coding error).
    /// </summary>
    public static readonly Coding Edit = new Coding
    {
      Code = "edit",
      Display = "Edit",
      System = "http://terminology.hl7.org/CodeSystem/message-reasons-encounter"
    };
    /// <summary>
    /// The patient has been moved to a new location.
    /// </summary>
    public static readonly Coding Moved = new Coding
    {
      Code = "moved",
      Display = "Moved",
      System = "http://terminology.hl7.org/CodeSystem/message-reasons-encounter"
    };
    /// <summary>
    /// The patient has returned from a temporary absence.
    /// </summary>
    public static readonly Coding Returned = new Coding
    {
      Code = "return",
      Display = "Returned",
      System = "http://terminology.hl7.org/CodeSystem/message-reasons-encounter"
    };

    /// <summary>
    /// Literal for code: Absent
    /// </summary>
    public const string LiteralAbsent = "absent";

    /// <summary>
    /// Literal for code: Admit
    /// </summary>
    public const string LiteralAdmit = "admit";

    /// <summary>
    /// Literal for code: Discharge
    /// </summary>
    public const string LiteralDischarge = "discharge";

    /// <summary>
    /// Literal for code: Edit
    /// </summary>
    public const string LiteralEdit = "edit";

    /// <summary>
    /// Literal for code: Moved
    /// </summary>
    public const string LiteralMoved = "moved";

    /// <summary>
    /// Literal for code: Returned
    /// </summary>
    public const string LiteralReturned = "return";
  };
}
