// <auto-generated />
// Built from: hl7.fhir.r4.core version: 4.0.1
  // Option: "NAMESPACE" = "fhirCsR4"

using fhirCsR4.Models;

namespace fhirCsR4.ValueSets
{
  /// <summary>
  /// This value set includes sample Information Category codes.
  /// </summary>
  public static class ClaimInformationcategoryCodes
  {
    /// <summary>
    /// Materials attached such as images, documents and resources.
    /// </summary>
    public static readonly Coding Attachment = new Coding
    {
      Code = "attachment",
      Display = "Attachment",
      System = "http://terminology.hl7.org/CodeSystem/claiminformationcategory"
    };
    /// <summary>
    /// Discharge status and discharge to locations.
    /// </summary>
    public static readonly Coding Discharge = new Coding
    {
      Code = "discharge",
      Display = "Discharge",
      System = "http://terminology.hl7.org/CodeSystem/claiminformationcategory"
    };
    /// <summary>
    /// An indication that the patient was unable to work, the period if known otherwise a Yes/No (boolean).
    /// </summary>
    public static readonly Coding EmploymentImpacted = new Coding
    {
      Code = "employmentimpacted",
      Display = "EmploymentImpacted",
      System = "http://terminology.hl7.org/CodeSystem/claiminformationcategory"
    };
    /// <summary>
    /// Insurance policy exceptions.
    /// </summary>
    public static readonly Coding Exception = new Coding
    {
      Code = "exception",
      Display = "Exception",
      System = "http://terminology.hl7.org/CodeSystem/claiminformationcategory"
    };
    /// <summary>
    /// The external cause of an illness or injury.
    /// </summary>
    public static readonly Coding ExternalCaause = new Coding
    {
      Code = "externalcause",
      Display = "External Caause",
      System = "http://terminology.hl7.org/CodeSystem/claiminformationcategory"
    };
    /// <summary>
    /// An indication that the patient was hospitalized, the period if known otherwise a Yes/No (boolean).
    /// </summary>
    public static readonly Coding Hospitalized = new Coding
    {
      Code = "hospitalized",
      Display = "Hospitalized",
      System = "http://terminology.hl7.org/CodeSystem/claiminformationcategory"
    };
    /// <summary>
    /// Codes conveying additional situation and condition information.
    /// </summary>
    public static readonly Coding Information = new Coding
    {
      Code = "info",
      Display = "Information",
      System = "http://terminology.hl7.org/CodeSystem/claiminformationcategory"
    };
    /// <summary>
    /// Materials being forwarded, e.g. Models, molds, images, documents.
    /// </summary>
    public static readonly Coding MaterialsForwarded = new Coding
    {
      Code = "material",
      Display = "Materials Forwarded",
      System = "http://terminology.hl7.org/CodeSystem/claiminformationcategory"
    };
    /// <summary>
    /// Teeth which are missing for any reason, for example: prior extraction, never developed.
    /// </summary>
    public static readonly Coding MissingTooth = new Coding
    {
      Code = "missingtooth",
      Display = "Missing Tooth",
      System = "http://terminology.hl7.org/CodeSystem/claiminformationcategory"
    };
    /// <summary>
    /// Period, start or end dates of aspects of the Condition.
    /// </summary>
    public static readonly Coding Onset = new Coding
    {
      Code = "onset",
      Display = "Onset",
      System = "http://terminology.hl7.org/CodeSystem/claiminformationcategory"
    };
    /// <summary>
    /// Other information identified by the type.system.
    /// </summary>
    public static readonly Coding Other = new Coding
    {
      Code = "other",
      Display = "Other",
      System = "http://terminology.hl7.org/CodeSystem/claiminformationcategory"
    };
    /// <summary>
    /// The reason for the patient visit.
    /// </summary>
    public static readonly Coding PatientReasonForVisit = new Coding
    {
      Code = "patientreasonforvisit",
      Display = "Patient Reason for Visit",
      System = "http://terminology.hl7.org/CodeSystem/claiminformationcategory"
    };
    /// <summary>
    /// The type of prosthesis and date of supply if a previously supplied prosthesis.
    /// </summary>
    public static readonly Coding Prosthesis = new Coding
    {
      Code = "prosthesis",
      Display = "Prosthesis",
      System = "http://terminology.hl7.org/CodeSystem/claiminformationcategory"
    };
    /// <summary>
    /// Nature and date of the related event e.g. Last exam, service, X-ray etc.
    /// </summary>
    public static readonly Coding RelatedServices = new Coding
    {
      Code = "related",
      Display = "Related Services",
      System = "http://terminology.hl7.org/CodeSystem/claiminformationcategory"
    };

    /// <summary>
    /// Literal for code: Attachment
    /// </summary>
    public const string LiteralAttachment = "attachment";

    /// <summary>
    /// Literal for code: ClaimInformationcategoryAttachment
    /// </summary>
    public const string LiteralClaimInformationcategoryAttachment = "http://terminology.hl7.org/CodeSystem/claiminformationcategory#attachment";

    /// <summary>
    /// Literal for code: Discharge
    /// </summary>
    public const string LiteralDischarge = "discharge";

    /// <summary>
    /// Literal for code: ClaimInformationcategoryDischarge
    /// </summary>
    public const string LiteralClaimInformationcategoryDischarge = "http://terminology.hl7.org/CodeSystem/claiminformationcategory#discharge";

    /// <summary>
    /// Literal for code: EmploymentImpacted
    /// </summary>
    public const string LiteralEmploymentImpacted = "employmentimpacted";

    /// <summary>
    /// Literal for code: ClaimInformationcategoryEmploymentImpacted
    /// </summary>
    public const string LiteralClaimInformationcategoryEmploymentImpacted = "http://terminology.hl7.org/CodeSystem/claiminformationcategory#employmentimpacted";

    /// <summary>
    /// Literal for code: Exception
    /// </summary>
    public const string LiteralException = "exception";

    /// <summary>
    /// Literal for code: ClaimInformationcategoryException
    /// </summary>
    public const string LiteralClaimInformationcategoryException = "http://terminology.hl7.org/CodeSystem/claiminformationcategory#exception";

    /// <summary>
    /// Literal for code: ExternalCaause
    /// </summary>
    public const string LiteralExternalCaause = "externalcause";

    /// <summary>
    /// Literal for code: ClaimInformationcategoryExternalCaause
    /// </summary>
    public const string LiteralClaimInformationcategoryExternalCaause = "http://terminology.hl7.org/CodeSystem/claiminformationcategory#externalcause";

    /// <summary>
    /// Literal for code: Hospitalized
    /// </summary>
    public const string LiteralHospitalized = "hospitalized";

    /// <summary>
    /// Literal for code: ClaimInformationcategoryHospitalized
    /// </summary>
    public const string LiteralClaimInformationcategoryHospitalized = "http://terminology.hl7.org/CodeSystem/claiminformationcategory#hospitalized";

    /// <summary>
    /// Literal for code: Information
    /// </summary>
    public const string LiteralInformation = "info";

    /// <summary>
    /// Literal for code: ClaimInformationcategoryInformation
    /// </summary>
    public const string LiteralClaimInformationcategoryInformation = "http://terminology.hl7.org/CodeSystem/claiminformationcategory#info";

    /// <summary>
    /// Literal for code: MaterialsForwarded
    /// </summary>
    public const string LiteralMaterialsForwarded = "material";

    /// <summary>
    /// Literal for code: ClaimInformationcategoryMaterialsForwarded
    /// </summary>
    public const string LiteralClaimInformationcategoryMaterialsForwarded = "http://terminology.hl7.org/CodeSystem/claiminformationcategory#material";

    /// <summary>
    /// Literal for code: MissingTooth
    /// </summary>
    public const string LiteralMissingTooth = "missingtooth";

    /// <summary>
    /// Literal for code: ClaimInformationcategoryMissingTooth
    /// </summary>
    public const string LiteralClaimInformationcategoryMissingTooth = "http://terminology.hl7.org/CodeSystem/claiminformationcategory#missingtooth";

    /// <summary>
    /// Literal for code: Onset
    /// </summary>
    public const string LiteralOnset = "onset";

    /// <summary>
    /// Literal for code: ClaimInformationcategoryOnset
    /// </summary>
    public const string LiteralClaimInformationcategoryOnset = "http://terminology.hl7.org/CodeSystem/claiminformationcategory#onset";

    /// <summary>
    /// Literal for code: Other
    /// </summary>
    public const string LiteralOther = "other";

    /// <summary>
    /// Literal for code: ClaimInformationcategoryOther
    /// </summary>
    public const string LiteralClaimInformationcategoryOther = "http://terminology.hl7.org/CodeSystem/claiminformationcategory#other";

    /// <summary>
    /// Literal for code: PatientReasonForVisit
    /// </summary>
    public const string LiteralPatientReasonForVisit = "patientreasonforvisit";

    /// <summary>
    /// Literal for code: ClaimInformationcategoryPatientReasonForVisit
    /// </summary>
    public const string LiteralClaimInformationcategoryPatientReasonForVisit = "http://terminology.hl7.org/CodeSystem/claiminformationcategory#patientreasonforvisit";

    /// <summary>
    /// Literal for code: Prosthesis
    /// </summary>
    public const string LiteralProsthesis = "prosthesis";

    /// <summary>
    /// Literal for code: ClaimInformationcategoryProsthesis
    /// </summary>
    public const string LiteralClaimInformationcategoryProsthesis = "http://terminology.hl7.org/CodeSystem/claiminformationcategory#prosthesis";

    /// <summary>
    /// Literal for code: RelatedServices
    /// </summary>
    public const string LiteralRelatedServices = "related";

    /// <summary>
    /// Literal for code: ClaimInformationcategoryRelatedServices
    /// </summary>
    public const string LiteralClaimInformationcategoryRelatedServices = "http://terminology.hl7.org/CodeSystem/claiminformationcategory#related";

    /// <summary>
    /// Dictionary for looking up ClaimInformationcategory Codings based on Codes
    /// </summary>
    public static Dictionary<string, Coding> Values = new Dictionary<string, Coding>() {
      { "attachment", Attachment }, 
      { "http://terminology.hl7.org/CodeSystem/claiminformationcategory#attachment", Attachment }, 
      { "discharge", Discharge }, 
      { "http://terminology.hl7.org/CodeSystem/claiminformationcategory#discharge", Discharge }, 
      { "employmentimpacted", EmploymentImpacted }, 
      { "http://terminology.hl7.org/CodeSystem/claiminformationcategory#employmentimpacted", EmploymentImpacted }, 
      { "exception", Exception }, 
      { "http://terminology.hl7.org/CodeSystem/claiminformationcategory#exception", Exception }, 
      { "externalcause", ExternalCaause }, 
      { "http://terminology.hl7.org/CodeSystem/claiminformationcategory#externalcause", ExternalCaause }, 
      { "hospitalized", Hospitalized }, 
      { "http://terminology.hl7.org/CodeSystem/claiminformationcategory#hospitalized", Hospitalized }, 
      { "info", Information }, 
      { "http://terminology.hl7.org/CodeSystem/claiminformationcategory#info", Information }, 
      { "material", MaterialsForwarded }, 
      { "http://terminology.hl7.org/CodeSystem/claiminformationcategory#material", MaterialsForwarded }, 
      { "missingtooth", MissingTooth }, 
      { "http://terminology.hl7.org/CodeSystem/claiminformationcategory#missingtooth", MissingTooth }, 
      { "onset", Onset }, 
      { "http://terminology.hl7.org/CodeSystem/claiminformationcategory#onset", Onset }, 
      { "other", Other }, 
      { "http://terminology.hl7.org/CodeSystem/claiminformationcategory#other", Other }, 
      { "patientreasonforvisit", PatientReasonForVisit }, 
      { "http://terminology.hl7.org/CodeSystem/claiminformationcategory#patientreasonforvisit", PatientReasonForVisit }, 
      { "prosthesis", Prosthesis }, 
      { "http://terminology.hl7.org/CodeSystem/claiminformationcategory#prosthesis", Prosthesis }, 
      { "related", RelatedServices }, 
      { "http://terminology.hl7.org/CodeSystem/claiminformationcategory#related", RelatedServices }, 
    };
  };
}
